# Generated by Django 5.1.6 on 2025-02-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personnale', '0001_initial'),
        ('custom_user', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('questions_ill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnale.ill')),
            ],
        ),
        migrations.CreateModel(
            name='UserSymptomChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_chosen', models.DateTimeField(auto_now_add=True)),
                ('resulta_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnale.ill')),
                ('symptoms', models.ManyToManyField(to='Personnale.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.person')),
            ],
        ),
    ]
