# Generated by Django 5.1.5 on 2025-01-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
        ('Personnale', '0002_symptom_remove_ill_symptoms_ill_symptoms'),
        ('custom_user', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSymptomChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_chosen', models.DateTimeField(auto_now_add=True)),
                ('resulta_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personnale.ill')),
                ('symptoms', models.ManyToManyField(to='Personnale.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.person')),
            ],
        ),
    ]
