# Generated by Django 5.1.5 on 2025-01-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ill',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='ill',
            name='symptoms',
            field=models.ManyToManyField(related_name='illnesses_symptoms', to='Personnale.symptom'),
        ),
    ]
