# Generated by Django 5.1.5 on 2025-01-29 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnale', '0004_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
