# Generated by Django 5.1.5 on 2025-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personnale', '0005_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ill',
            name='symptoms',
            field=models.ManyToManyField(related_name='illnesse_symptoms', to='Personnale.symptom'),
        ),
    ]
